### ISSUE TITLE
JSON.parse failure for KPI blob should be 400 Bad Request, not 500 Internal Server Error

### ISSUE THREAD

**Issue by kparlante** [mozilla/kpiggybank#10]
Originally filed in https://github.com/jedp/kpiggybank/issues/7

Maybe a nit but 500 errors should be reserved for "Oh shit. I have no idea what's happening". Fending off bad JSON input should be a 400 error.

See around https://github.com/mozilla/kpiggybank/blob/master/lib/server.js#L119

**Comment by lloyd** [comment]
Not a nit, Important for passive monitoring.

-- lloyd (thumb-typing)
