### ISSUE TITLE
Should be able to start server up easily if it has been stopped

### ISSUE THREAD

**Issue by kparlante** [mozilla/kpiggybank#14]
We wanted to stop the server during load to see what would happen to browserid, but can't find a way to bring up kpiggybank again cleanly after forever stopall. Perhaps we want to invoke post-update.js with the right context.

**Comment by jedp** [comment]
Does `forever restartall` not work?

If there's not a kpiggybank-specific issue, this might be a good general feature to have for awsbox - remote stop and start, including instances where `forever` won't restart.

**Comment by kparlante** [comment]
'forever restartall' only works if the process(es) are still running. Yes, this isn't specific to kpiggybank, it would be great to have an awsbox feature to call forever start with the right environment & options. (Perhaps an easy way to do this already exists, just haven't figured it out!)

**Comment by lloyd** [comment]
```
$ cd ~app/git
$ ../post-update.js
```

:wink:
