### ISSUE TITLE
There appears to be a memory leak with the collector

### ISSUE THREAD

**Issue by kparlante** [mozilla/kpiggybank#15]
From https://github.com/jedp/kpiggybank/issues/8, logged by @jrgm

In the process of driving some high load for interaction_data against the collector, it was noticed that RSS was steadily growing. I suspect there is a leak in that code path, but haven't looked further. And it wasn't a careful experiment as I was playing with kill and iptables tricks before it was noticed, so I may have set the collector on a bad code path (but still...).

Anyways, this could use some investigation in a clone of the kpiggybank-stage instance.

**Comment by jrgm** [comment]
Yeah, I saw this again. The RSS for the collector was 1.3GB on kpiggybank-stage. The max heap for v8 is, I forget exactly what, but about 1.7GB, and the process will die at that point.

**Comment by kparlante** [comment]
I'll take a look at this

**Comment by kparlante** [comment]
I wired up an ephemeral instance with memwatch, and noticed a lot of arrays, strings and numbers hanging on. To me, this suggested cradle might be the problem (not a lot else is happening in a post). Google "cradle node memory leak" and you see others noticing the same pattern: http://louis.chefbe.net/wp/?p=30 Cradle has a write through cache, turned on by default, which we don't need. Setting cache:false and raw:true seems to alleviate the rapid memory growth, resident memory stays in a narrower range. PR on its way. (I'd also like to poke around a heap snapshot)

**Comment by kparlante** [comment]
for the record, I was wrong about raw:true (oops)

**Comment by jrgm** [comment]
After 3 hours at 500K ADU load_gen, the RSS has been steadily between 60 and 100 MB of RSS.

**Comment by jrgm** [comment]
I think we can call this closed (but apparently, I can't close issues in this repo).

**Comment by kparlante** [comment]
Pushed to production.
