### ISSUE TITLE
For production instance, implement a watchdog killer if 127.0.0.1:10000 on kpi collector is non-responsive

### ISSUE THREAD

**Issue by jrgm** [mozilla/kpiggybank#22]
This is information we can afford to lose. But we had a hang of the stage collector, and later it occurred to me that this would have had negative implications for the webheads (we have a fix to address that, but still, if this thing hangs again, I'd prefer to just restart it).

**Comment by kparlante** [comment]
Won't fix unless other fixes fall through (make persona more resilient, fix memory leak). Re-raise if necessary.
