### ISSUE TITLE
kpiggybank-stage slowed in throughput during a long loadtest on aws browserid stage environment.

### ISSUE THREAD

**Issue by jrgm** [mozilla/kpiggybank#23]
About 2013-04-22T12:00, the throughput of POSTs recorded in /home/app/code/kpiggybank.log dropped from ~15 req/sec to ~2 req/sec. This then caused the browserid processes to begin buffering up the KPI blobs in memory, so RSS on that process grew from the normal ~60MB to ~200MB, and would have kept growing until max heap size for v8 was exceeded and the browserid process would have crashed.

Not sure how to debug this further, as the logs say very little. 

I restarted kpiggybank-stage, and the backlog of requests on the browserid process eventually cleared.

**Comment by kparlante** [comment]
I'll take a look

**Comment by jrgm** [comment]
Since the fix in #24 for #15, this has not been seen in a 24hour load_gen run.

Closing.
