### ISSUE TITLE
Revisit architecture for sending data from browserid to kpiggybank

### ISSUE THREAD

**Issue by kparlante** [mozilla/kpiggybank#4]
The original plan was to use http (when everything lived behind mozilla firewall).

Moving to AWS, the current plan is to use https.

It has been suggested we move to use UDP. Another thought was to write to the filesystem and have a separate process send the data to kpiggybank.

Don't block on this, but take another look at it after we get up and running.

**Comment by lloyd** [comment]
I suggest we first do mozilla/browserid#3295 - use HTTP as it stands with a more robust delivery implementation, then see if we need to go deeper.
